blog/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import home,matlablistuser,signup,log_in,log_out,contact,panel,addmatlab,searchmatlabs,editmatlab,deletematlab,homematlab,detail

urlpatterns = [
    path('',homematlab,name="home"),
    path('signup/', signup, name='signup'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    path("contact/", contact, name="contact"),
    path("panel/", panel, name="panel"),
    path("addmatlab/", addmatlab, name="addmatlab"),
    path("matlabs/", searchmatlabs, name="searchmatlabs"),
    path("mymatlabs/", matlablistuser , name="matlabslistuser"),
    path(r'editmatlab/(?P<id>)', editmatlab , name="editmatlab"),
    path(r'deletematlab/(?P<id>)', deletematlab , name="deletematlab"),
    url(r'^(?P<id>[0-9]{1,3})$', views.detail , name='detail'),
]

proju/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('blog.urls' , 'blog') , namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
User = get_user_model()
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.urls import reverse


class matlabs(models.Model):
    id = models.AutoField(primary_key=True)
    author = models.ForeignKey(User, null=True, blank=True,on_delete=models.CASCADE)
    title = models.CharField(max_length=70)
    mohtava = models.TextField()
    updatedatetime = models.DateTimeField(('create date'), auto_now_add=True, auto_now=False)
    createdatetime = models.DateTimeField(('update date'), auto_now_add=False, auto_now=True)

    def human_readable_title(self):
        return self.title.replace(' ', '_')
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'id':self.id})

blog/forms.py
from django import forms
from .models import matlabs
from django.forms import ModelForm
from . import models


#class contactform(forms.Form):
  #  form_email = forms.EmailField(required=True)
   # subject = forms.CharField(required=True)
   # message = forms.CharField(widget=forms.Textarea, required=True)

class matlabform(ModelForm):
    class Meta:
       model = models.matlabs
       fields = ('title','mohtava')

blog/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User,Group
from django.shortcuts import render , get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.mail import send_mail
from .models import matlabs
from .forms import matlabform
from django.urls import reverse
from django.db.models import Q

def home(request):
    writer, created = Group.objects.get_or_create(name='writer')
    return render(request,"base.html")

def signup(request):
    error_pass = False
    error_user = False
    error_null = False
    if request.method == 'POST':
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        username = request.POST.get("username")
        email = request.POST.get("email")
        password = request.POST.get("password1")
        password_repeat = request.POST.get("password2")

        if username=='' or email=='' or password=='' or password_repeat=='' :
            error_null = True
            return render(request, "signup.html",{"error_null":error_null})

        if password != password_repeat :
            error_pass = True
            return render(request, "signup.html", {"error_pass": error_pass})

        if User.objects.filter(username=username).exists() :
            error_user = True
            return render(request, "signup.html", {"error_user": error_user})

        user = User.objects.create_user(first_name=first_name, last_name=last_name, username=username, email=email)
        user.set_password(password)
        user.save()

        return HttpResponseRedirect("/")
    return render(request, "signup.html")

def log_in(request):
    error_login = False
    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect("/")
        elif user is None:
            error_login = True
    return render(request, "login.html", {
        "error_login": error_login
    })

def log_out(request):
    logout(request)
    return HttpResponseRedirect("/")

def contact(request):
    if request.method == 'POST':
        title = request.POST.get("title")
        text = request.POST.get("text")
        email = request.POST.get("email")
        send_mail(
                title,
                f"{text}  {email}",
                'email@a.com',
                ["email2@a.com"],
            )
        return render(request, "contact-success.html")
    return render(request, "contact.html")

def panel(request):
    writer, created = Group.objects.get_or_create(name='writer')
    flagg = False
    if request.method == 'POST':
        writer.user_set.add(request.user)
        return render(request, "writer-done.html",{"flagg": flagg})
    if request.user.groups.filter(name = 'writer').exists():
        flagg = True
    else:
        flagg = False
    print(flagg)
    return render(request, "panel.html",{"flagg": flagg})

def addmatlab(request):
    writer, created = Group.objects.get_or_create(name='writer')
    flagg = False
    if request.user.groups.filter(name = 'writer').exists():
        flagg = True
        print(flagg)
    else:
        flagg = False
        print(flagg)
    if request.method == 'POST':
        title = request.POST.get("title")
        mohtava = request.POST.get("mohtava")
        matlab = matlabs(title=title,mohtava=mohtava,author=request.user)
        matlab.save()
        return render(request, "matlab-success.html")
    return render(request, "addmatlab.html",{"flagg": flagg})
  
def matlablistuser(request):
    user_matlabs = matlabs.objects.filter(author=request.user)
    return render(request, "usermatlabs.html",{"user_matlabs":user_matlabs})

def searchmatlabs(request):
    error_search = False
    searchmatlabs = matlabs.objects.all()
    if request.method == "POST":
        query = request.POST.get("title")
        search_list = matlabs.objects.filter(title__contains=query)
        if not search_list.all().exists() :
            error_search = True
            print(1)
            return render(request, "matlabs.html", {"error_search": error_search})
        else:
            return render(request, "search.html", {"search_list": search_list })
    return render(request, "matlabs.html",{"searchmatlabs":searchmatlabs})

def editmatlab(request , id=None):
    post = get_object_or_404(matlabs, id=id)
    editform = matlabform(request.POST or None , request.FILES or None, instance=post)
    if editform.is_valid():
        editform.save()
        return HttpResponseRedirect('/mymatlabs')
    context = {
        'form': editform,
    }
    return render(request, 'editmatlab.html',context)

def deletematlab(request , id=None):
    post = get_object_or_404(matlabs, id=id)
    if post.delete():
        return HttpResponseRedirect('/mymatlabs')

def homematlab(request):
    postha = matlabs.objects.all()
    context = {
        'postha' : postha
    }
    print(postha.all())
    return render(request, 'base.html',context)

def detail(request , id=None):
    post = get_object_or_404(matlabs, id=id)
    context = {
        'post' : post
    }
    return render(request, 'detail.html' , context)

blog/templates/addmatlab.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
{{block.super}} | پست جدید 
{% endblock title %}

{% block content %}

    <div
        class="p-5 text-center bg-image"
        style="
        background-image: url('{% static 'media/bg1.jpg' %}');
        height: 100%;
        "
    >
    <div class="rounded-lg mask" style="background-color: rgba(0, 0, 0, 0.2);">
    <div class="d-flex justify-content-center align-items-center h-100">


    {% if flagg == True %}
            <div class="container mb-5 mt-5">
                <div class="row mx-auto">
                    <div class="col">
                        <div class="card">
                            <div class="card-header bg-secondary text-white text-center"><i class="fa fa-envelope"></i> ایجاد پست جدید
                            </div>
                            <div class="card-body">
                                <form action="/addmatlab/" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="title">عنوان پست</label>
                                        <input type="text" name="title" class="form-control" aria-describedby="titlematlab" placeholder="عنوان پست را وارد کنید" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="mohtava">متن پست</label>
                                        <textarea type="text" name="mohtava" class="form-control" aria-describedby="mohatava" placeholder="متن پست" required></textarea>
                                    </div>
                                    <div class="d-flex my-2">
                                    <button type="submit" class="btn btn-outline-success text-center mx-auto" style="width: 150px;">ارسال پست</button></div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    {% else %}
    شما نویسنده نیستید
    {% endif %}




    </div>
    </div>
    </div>

{% endblock content %}

blog/templates/base.html
{% load static %}

<DOCTYPE html>
<html lang="en" dir="rtl">
<head>

    {% block meta %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% endblock meta %}

    <title>
    {% block title %}
    نیملاگ؛ بلاگ شخصی نیما امینی
    {% endblock title %}
    </title>

    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% endblock css %}
    
</head>

<body>


    <!--#################################### header ##########################################-->
    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top shadow">
        <div class="container-fluid">
        
        <div class="collapse navbar-collapse">
            <ul class="nav nav-light-success nav-pills">
                <li class="nav-item">
                    <a id="li-faal" class="nav-link active" href="/">صفحه اصلی</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/contact/">تماس با ما</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/matlabs/">جستجو</a>
                </li>

                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="/panel/">پنل کاربری</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/logout/">خروج</a>
                    </li>

                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/login/">ورود</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/signup/">ثبت نام</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        </div>
    </nav>

    {% endblock navbar %}

    <!-- Background image -->

    {% block content %}

    <style>
        .rounded{
            border-radius:30px !important;
        }
    </style>

    <br>
    <br>

    <div
        class="p-5 text-center bg-image"
        style="
        background-image: url('{% static 'media/bg1.jpg' %}');
        height: 95%;
        "
    >
        <div class="rounded mask" style="background-color: rgba(0, 0, 0, 0.2);">
        <div class="d-flex justify-content-center align-items-center h-100">
            <div class="text-white">
            <p class="mb-3" style="font-size:60px;"><b>نیملاگ؛ بلاگ شخصی نیما امینی</b></p>
            <h4 class="mb-3">نکات آموزشی کوتاه در رابطه با گرافیک دیزاین</h4>
            <button type="button" class="btn btn-outline-light">
                <a id="link-matlab" class="dropdown-item" href="#matlabha">مطالب</a>
            </button>
            </div>
        </div>
        </div>
    </div>
    <!--#################################### mataleb ###################################-->

<br>
<br>    

        <div id="matlabha" class="d-flex justify-content-center align-items-center">
            <div class="text">
            <h2 class="mb-3 text-gray"><b>مطالب وبلاگ</b></h2>
            </div>
        </div>


                {% for p in postha %}

                    <div class="container rounded shadow " style="background-color: rgba(255,255,255, 1);">
                        <div class="row">
                        <div class="col-lg-11 col-md-10 mx-auto">
                            <div class="post-preview" align="right">
                                <br>

                                <!-- # title matlab #-->
                                <a href="{{ p.get_absolute_url }}">
                                    <h3 class="post-title"><b>{{ p.title }}</b></h3>
                                </a>
                                <br>

                                <!-- # mohtava matlab #-->
                                <p class="post-subtitle">{{ p.mohtava|safe|truncatechars:150 }}</p>
                                <br>
                                <hr>

                                <!-- # detail #-->  
                                <p class="post-meta">
                                نویسنده : {{ p.author.username }}
                                |
                                زمان انتشار :  {{ p.createdatetime }}

                                </p>
                                </div>
                            </div>
                            </div>
                        </div>
                        </div>

                        <br>
                        <br>
                        <br>


                {% endfor %}

    {% endblock content %}

    {% block footer %}
    
        <footer class="page-footer font-small bg-secondary">

            <!-- Footer Elements -->
            <div class="container">

                <!-- Call to action -->
                <ul class="list-unstyled list-inline text-center py-2">
                <li class="list-inline-item">
                    <h5 class="mb-1"></h5>
                </li>
                </ul>
                <!-- Call to action -->

            </div>
            <!-- Footer Elements -->

            <!-- Copyright -->
            <div class="footer-copyright text-center py-3 text-white bg-dark">Devepoled by Nima Amini | 2021 Nimart
            </div>
            <!-- Copyright -->

        </footer>
        <!-- Footer -->

    {% endblock footer %}
    





    {% block js %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock js %}
    
</body>
</html>

blog/templates/contact-success.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
{{block.super}} | تماس با ما
{% endblock title %}

{% block content %}

    <div
        class="p-5 text-center bg-image"
        style="
        background-image: url('{% static 'media/bg1.jpg' %}');
        height: 100%;
        "
    >
    <div class="rounded-lg mask" style="background-color: rgba(0, 0, 0, 0.2);">
    <div class="d-flex justify-content-center align-items-center h-100">

    <div>
        <div class="alert alert-success text-right text-center mx-auto mt-4 w-50" role="alert" dir="rtl">
    درخواست شما ثبت شد
    <br>
        <a href="/contact/" class="my-3 btn btn-outline-success text-center mx-auto" style="width: 150px;">ارسال پیام مجدد</a>

    </div>
        </div>



    </div>
    </div>

    {% endblock content %}

blog/templates/contact.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
{{block.super}} | تماس با ما
{% endblock title %}


{% block content %}
    <div
        class="p-5 text-center bg-image"
        style="
        background-image: url('{% static 'media/bg1.jpg' %}');
        height: 100%;
        "
    >
    <div class="rounded-lg mask" style="background-color: rgba(0, 0, 0, 0.2);">
    <div class="d-flex justify-content-center align-items-center h-100">

        <div class="container mb-5 mt-5">
            <div class="row mx-auto">
                <div class="col">
                    <div class="card">
                        <div class="card-header bg-secondary text-white text-center"><i class="fa fa-envelope"></i> تماس با ما
                        </div>
                        <div class="card-body">
                            <form action="/contact/" method="post">
                                {% csrf_token %}
                                <div class="form-group ">
                                    <label for="title">موضوع</label>
                                    <input type="text" name="title" class="form-control" aria-describedby="emailHelp" placeholder="عنوان را وارد کنید" required>
                                </div>
                                <div class="form-group">
                                    <label for="email">ایمیل</label>
                                    <input type="email" name="email" class="form-control" aria-describedby="email" placeholder="ایمیل شما" required>
                                </div>
                                <div class="form-group">
                                    <label for="message">پیام</label>
                                    <textarea class="form-control" name="text" rows="6" minlength="10" maxlength="250" placeholder="یک پیام بین حداقل ۱۰ و حداکثر ۲۵۰ کاراکتر وارد کنید" required></textarea>
                                </div>
                                <div class="d-flex my-2">
                                <button type="submit" class="btn btn-outline-success text-center mx-auto" style="width: 150px;">ارسال</button></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>




    </div>
    </div>
    </div>

    {% endblock content %}

blog/templates/detail.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
{{block.super}} | matlab
{% endblock title %}


{% block content %}

<br>
<br>
<br>
<br>

        <style>
        .rounded{
            border-radius:30px !important;
        }
        </style>



        <div class="container rounded shadow " style="background-color: rgba(255,255,255, 1);">
            <div class="row">
            <div class="col-lg-11 col-md-10 mx-auto">
                <div class="post-preview" align="right">
                    <br>
                    <br>

                    <!-- # title matlab #-->
                    <a href="{{ post.get_absolute_url }}">
                        <h1 class="post-title"><b>{{ post.title }}</b></h1>
                    </a>
                    <br>
                    <br>

                    <!-- # mohtava matlab #-->
                    <p class="post-subtitle">{{ post.mohtava }}</p>
                    <br>
                    <br>
                    <hr>

                    <!-- # detail #-->  
                    <p class="post-meta">
                      نویسنده : {{ post.author.username }}
                    |
                    زمان انتشار :  {{ post.createdatetime }}

                    </p>
                    </div>
                </div>
                </div>
            </div>
            </div>

            <br>
            <br>
            <br>

{% endblock content %}

blog/templates/editmatlab.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}


{% block title %}
{{block.super}} | ویرایش مطلب
{% endblock title %}


{% block content %}

<br>
<br>
<br>

<div class="container mb-5 mt-5">
    <style>
    </style>
    <div class="row mx-auto">
        <div class="col">
            <div class="card">
                <div class="card-header bg-secondary text-white text-center"><i class="fa fa-envelope"></i> ویرایش مطلب
                </div>
                <div class="card-body" align="right">
                    <form method="post" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-primary" type="submit">{% trans "ذخیره" %}</bottun>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

blog/templates/login.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
{{block.super}} | ورود
{% endblock title %}

{% block navbar %}{% endblock navbar %}

{% block content %}

    <div
        class="p-5 text-center bg-image"
        style="
        background-image: url('{% static 'media/bg1.jpg' %}');
        height: 100%;
        "
    >
    <div class="rounded-lg mask" style="background-color: rgba(0, 0, 0, 0.2);">
        <div class="d-flex justify-content-center align-items-center h-100">

    <form class="d-felx container w-50 justify-content-center validate-form" action="/login/" method="post">
        {% csrf_token %}
        {% if error_login %}
        <div class="container">
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong></strong>نام کاربری یا رمز عبور اشتباه است{{error}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
        {% endif %}
        <div class="wrap-input100 validate-input" data-validate="Username is required">
            <label class="my-2 text-white">نام کاربری</label>
            <input name="username" class="form-control" type="text" placeholder="یک نام کاربری وارد کنید">
        </div>

        <div class="wrap-input100 validate-input" data-validate="Password is required">
            <label class="my-2 text-white">رمز عبور</label>
            <input class="form-control" type="password" name="password" placeholder="رمز عبورتان را وارد کنید">
        </div>

        <div class="m-4 text-left">
            <button class="btn btn-primary" type="submit" name="submit">
                ورود
            </button>
        </div>
        <a class="nav-link active text-white" href="/">بازگشت به صفحه اصلی سایت</a>
    </form>


    </div>
    </div>
    </div>

{% endblock content %}

blog/templates/matlab-success.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
{{block.super}} | ایجاد مطلب
{% endblock title %}

{% block content %}

    <div
        class="p-5 text-center bg-image"
        style="
        background-image: url('{% static 'media/bg1.jpg' %}');
        height: 100%;
        "
    >
    <div class="rounded-lg mask" style="background-color: rgba(0, 0, 0, 0.2);">
    <div class="d-flex justify-content-center align-items-center h-100">

    <div>
    <div class="alert alert-success text-right text-center mx-auto mt-4 w-100" role="alert" dir="rtl"> مطلب شما ایجاد شد
    <br>
    <a href="/addmatlab/" class="my-3 btn btn-outline-success text-center mx-auto" style="width: 150px;"> ایجاد مطلب جدید </a>

    </div>
    </div>


    </div>
    </div>
    </div>

{% endblock content %}

blog/templates/matlabs.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
{{block.super}} | جستجو
{% endblock title %}


{% block content %}

    <style>
        .rounded{
            border-radius:30px !important;
        }
    </style>

    <br>
    <br>
    <div
        class="p-5 text-center bg-image"
        style="
        background-image: url('{% static 'media/bg1.jpg' %}');
        height: 34%;
        "
    >
        <div class="rounded mask" style="background-color: rgba(0, 0, 0, 0.2);">
        <div class="col-md-4 mx-auto mb-5 justify-content-center align-items-center h-100">
        <br>
            <div class="text-white">
            <div>
                <form action="/matlabs/" method="POST" dir="rtl" class="my-2">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" name="title" placeholder="جستجو در مطالب">
                </div>
                <div class="d-flex my-2">
                    <button name="submit" type="submit" class="btn btn-success text-center mx-auto bg-dark" style="width: 150px;">جست و جو</button></div>
                </form>
            </div>
            </div>
        </div>
        </div>
    </div>
    <br>
    <br>
    <br>
            {% if error_search %}
    
            <h2 class="h2 col-12 text-center py-3 " style="color:red;"><b>متاسفانه مطلبی یافت نشد :(</b></h2>

            {% else %}

        
        <div>
            <h2 class="h2 col-12 text-center py-3 text-dark"><b>نتیجه جست و جو</b></h2>
            <br>
                {% for matlab in searchmatlabs %}

                    <div class="container rounded shadow {{ matlab.human_readable_title }}_{{ matlab.author.username }}" style="background-color: rgba(255,255,255, 1);">
                        <div class="row">
                        <div class="col-lg-11 col-md-10 mx-auto">
                            <div class="post-preview" align="right">
                                <br>

                                <!-- # title matlab #-->
                                <a href="{{ matlab.get_absolute_url }}">
                                    <h3 class="post-title"><b>{{ matlab.title }}</b></h3>
                                </a>
                                <br>

                                <!-- # mohtava matlab #-->
                                <p class="post-subtitle">{{ matlab.mohtava|safe|truncatechars:150 }}</p>
                                <br>
                                <hr>

                                <!-- # detail #-->  
                                <p class="post-meta">
                                نویسنده : {{ matlab.author.username }}
                                |
                                زمان انتشار :  {{ matlab.createdatetime }}

                                </p>
                                </div>
                            </div>
                            </div>
                        </div>
                        </div>

                        <br>
                        <br>
                        <br>


                {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}


    </div>
    </div>
    </div>

    <br>
    <br>


        </div>
    </div>
    </div>

{% endblock content %}

blog/templates/usermatlabs.html
{% extends 'base.html' %}

{% load static %}


{% block title %}
{{block.super}} | نوشته های من
{% endblock title %}

{% block content %}

    <style>
        .rounded{
            border-radius:30px !important;
        }
    </style>

    <br>
    <br>
    <br>            
        <div>
            <h2 class="h2 col-12 text-center py-3 text-dark"><b>مطالب ارسالی شما</b></h2>
            <br>
                {% for user_matlab in user_matlabs %}

                    <div class="container rounded shadow {{ user_matlab.title }}_{{ user_matlab.author.username }}" style="background-color: rgba(255,255,255, 1);">
                        <div class="row">
                        <div class="col-lg-11 col-md-10 mx-auto">
                            <div class="post-preview" align="right">
                                <br>

                                <!-- # title matlab #-->
                                <a href="{{ user_matlab.get_absolute_url }}">
                                    <h3 class="post-title"><b>{{ user_matlab.title }}</b></h3>
                                </a>
                                <br>

                                <!-- # mohtava matlab #-->
                                <p class="post-subtitle">{{ user_matlab.mohtava|safe|truncatechars:150 }}</p>
                                <br>
                                <hr>

                                <!-- # detail #-->  
                                <p class="post-meta">
                                نویسنده : {{ user_matlab.author.username }}
                                |
                                زمان انتشار :  {{ user_matlab.createdatetime }}
                                <br>
                                <br>
                                <br>
                                <button type="button" class="btn btn-success left">
                                <a class="text-white"  id="edit_{{ user_matlab.title }}_{{ user_matlab.author.username }}" href="{% url 'blog:editmatlab' id=user_matlab.id %}">ویرایش مطلب</a>
                                </button>
                                <button type="button" class="btn btn-danger">
                                <a class="text-white" id="delete_{{ user_matlab.title }}_{{ user_matlab.author.username }}" href="{% url 'blog:deletematlab' id=user_matlab.id %}">حذف مطلب</a>
                                </button>

                                </p>
                                </div>
                            </div>
                            </div>
                        </div>
                        </div>

                        <br>
                        <br>
                        <br>


                {% endfor %}
            </div>
        </div>
    </div>


    </div>
    </div>
    </div>

    <br>
    <br>

    {% endblock content %}